# Generated by Django 4.2.1 on 2023-07-21 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0002_ordermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderModel',
        ),
    ]
