# Generated by Django 4.2.1 on 2023-07-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0003_delete_ordermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=10)),
                ('is_expired', models.BooleanField(default=False)),
                ('discount_price', models.IntegerField(default=100)),
                ('min_req_amount', models.IntegerField(default=500)),
            ],
        ),
    ]
